In [36]:
#import the necessary packaged for managing datasets
import pandas as pd
import datetime
from datetime import datetime as dt

In [37]:
# Read the CSV  file containing all the datafields
a = pd.read_csv("pidfwithlatlong.csv",names = ['trip_id', 'start_time', 'stop_time', 'bike_id', 'trip_duration','from_station_id', 'from_station_name', 'to_station_id','station_name', 'user_type  ', 'from_latitude', 'from_longitude','to_latitude', 'to_longitude', 'DATE', 'AWND', 'PRCP', 'TMAX', 'TMIN', 'WT01', 'WT02', 'WT03', 'WT04', 'WT08', 'WT09', 'season', 'holiday','walk_score', 'transit_score', 'bike_score', 'distance'] ,header = 0)

In [38]:
# Display first 3 observations
a.head(3)

,trip_id,start_time,stop_time,bike_id,trip_duration,from_station_id,from_station_name,to_station_id,station_name,user_type,...,WT03,WT04,WT08,WT09,season,holiday,walk_score,transit_score,bike_score,distance
0,10676972,2015-05-31 06:54:00,2015-05-31 10:17:00,70166,12190,1018,Butler St & Stanton Ave,1001,Forbes Ave & Market Square,Customer,...,NaN,NaN,NaN,NaN,spring,1,90,62,75,2.669996
1,10684485,2015-05-31 09:39:00,2015-05-31 10:34:00,70289,3290,1018,Butler St & Stanton Ave,1001,Forbes Ave & Market Square,Customer,...,NaN,NaN,NaN,NaN,spring,1,90,62,75,2.669996
2,10686345,2015-05-31 10:20:00,2015-05-31 10:54:00,70368,2005,1018,Butler St & Stanton Ave,1001,Forbes Ave & Market Square,Customer,...,NaN,NaN,NaN,NaN,spring,1,90,62,75,2.669996

In [39]:
## Display the columns
a.columns

Index(['trip_id', 'start_time', 'stop_time', 'bike_id', 'trip_duration',
       'from_station_id', 'from_station_name', 'to_station_id', 'station_name',
       'user_type  ', 'from_latitude', 'from_longitude', 'to_latitude',
       'to_longitude', 'DATE', 'AWND', 'PRCP', 'TMAX', 'TMIN', 'WT01', 'WT02',
       'WT03', 'WT04', 'WT08', 'WT09', 'season', 'holiday', 'walk_score',
       'transit_score', 'bike_score', 'distance'],
      dtype='object')

In [40]:
#Rounding off the distance from original station to destination station to 2 decimal places after decimal
a["distance"] = a["distance"].round(2)

In [41]:
#Since we don't need latitudes and longitudes in our final  analysis, dropping off those columns
a.drop(['from_latitude', 'from_longitude','to_latitude', 'to_longitude'], inplace = True, axis = 1)

In [42]:
#Analysing the columns

a.columns

Index(['trip_id', 'start_time', 'stop_time', 'bike_id', 'trip_duration',
       'from_station_id', 'from_station_name', 'to_station_id', 'station_name',
       'user_type  ', 'DATE', 'AWND', 'PRCP', 'TMAX', 'TMIN', 'WT01', 'WT02',
       'WT03', 'WT04', 'WT08', 'WT09', 'season', 'holiday', 'walk_score',
       'transit_score', 'bike_score', 'distance'],
      dtype='object')

In [43]:
# Coverting "Rentals" df to the same datetime format as "Storm" df before merging
dts = [datetime.datetime.strptime(elem, '%Y-%m-%d %H:%M:%S') 
       for elem in a["start_time"]]
fmted = [elem.strftime('%Y-%m-%d %H:%M:%S') for elem in dts]

a.insert(0, 'start_time1', fmted)

In [44]:
a.head(2)

,start_time1,trip_id,start_time,stop_time,bike_id,trip_duration,from_station_id,from_station_name,to_station_id,station_name,...,WT03,WT04,WT08,WT09,season,holiday,walk_score,transit_score,bike_score,distance
0,2015-05-31 06:54:00,10676972,2015-05-31 06:54:00,2015-05-31 10:17:00,70166,12190,1018,Butler St & Stanton Ave,1001,Forbes Ave & Market Square,...,NaN,NaN,NaN,NaN,spring,1,90,62,75,2.67
1,2015-05-31 09:39:00,10684485,2015-05-31 09:39:00,2015-05-31 10:34:00,70289,3290,1018,Butler St & Stanton Ave,1001,Forbes Ave & Market Square,...,NaN,NaN,NaN,NaN,spring,1,90,62,75,2.67

In [45]:
# Creating a copy of the original df
q = a.copy()

In [46]:
# Display the number of rows and columns
q.shape

(267512, 28)

In [47]:
# Display first  observation from the copied df
q.head(1)

,start_time1,trip_id,start_time,stop_time,bike_id,trip_duration,from_station_id,from_station_name,to_station_id,station_name,...,WT03,WT04,WT08,WT09,season,holiday,walk_score,transit_score,bike_score,distance
0,2015-05-31 06:54:00,10676972,2015-05-31 06:54:00,2015-05-31 10:17:00,70166,12190,1018,Butler St & Stanton Ave,1001,Forbes Ave & Market Square,...,NaN,NaN,NaN,NaN,spring,1,90,62,75,2.67

In [48]:
# Reading the "Storms" dataset
r = pd.read_csv("Pi_storm.csv", names = ["start_time1", "event_type"], header = 0)

In [49]:
#Coverting the common datafields to similar datetime objects
q["start_time1"] =q["start_time1"].astype('datetime64[ns]')
r["start_time1"] =r["start_time1"].astype('datetime64[ns]')

In [50]:
#Adding another  temporary Date column to match on these columns before performing pd.asof() merge operation.
q["DATE"] = pd.to_datetime(q['start_time1']).dt.date

In [53]:
r["DATE"] = pd.to_datetime(r["start_time1"]).dt.date

In [54]:
#Display the first row
r.head(1)

          start_time1         event_type        DATE
0 2015-04-09 16:59:00  Thunderstorm Wind  2015-04-09

In [55]:
"""Performing time series merge using Date & Time by using the common Field name to join on ( on='start_time1' column).
For each row in the left "q" dataFrame, only rows from the right DataFrame ("r") whose 'on' column values match the
 the timedelta value of within tolerance range(1 hour) to  will be kept"""

s = pd.merge_asof(q.sort_values(by ="start_time1") ,r.sort_values(by ="start_time1") , on='start_time1', by ="DATE", tolerance=pd.Timedelta(hours=1)).fillna('NAN')

In [56]:
#Display first five observations
s.head()

,start_time1,trip_id,start_time,stop_time,bike_id,trip_duration,from_station_id,from_station_name,to_station_id,station_name,...,WT04,WT08,WT09,season,holiday,walk_score,transit_score,bike_score,distance,event_type
0,2015-05-31 06:54:00,10676972,2015-05-31 06:54:00,2015-05-31 10:17:00,70166,12190,1018,Butler St & Stanton Ave,1001,Forbes Ave & Market Square,...,NAN,NAN,NAN,spring,1,90,62,75,2.67,NAN
1,2015-05-31 06:57:00,10677086,2015-05-31 06:57:00,2015-05-31 09:24:00,70368,8842,1018,Butler St & Stanton Ave,1018,Butler St & Stanton Ave,...,NAN,NAN,NAN,spring,1,90,62,75,0.00,NAN
2,2015-05-31 06:58:00,10677131,2015-05-31 06:58:00,2015-05-31 10:09:00,70354,11448,1019,42nd St & Butler St,1019,42nd St & Butler St,...,NAN,NAN,NAN,spring,1,86,51,77,0.00,NAN
3,2015-05-31 07:08:00,10677525,2015-05-31 07:08:00,2015-05-31 07:15:00,70232,452,1001,Forbes Ave & Market Square,1001,Forbes Ave & Market Square,...,NAN,NAN,NAN,spring,1,99,100,87,0.00,NAN
4,2015-05-31 07:15:00,10677886,2015-05-31 07:15:00,2015-05-31 09:27:00,70468,7866,1018,Butler St & Stanton Ave,1018,Butler St & Stanton Ave,...,NAN,NAN,NAN,spring,1,90,62,75,0.00,NAN

In [57]:
s.shape

(267512, 29)

In [58]:
s.event_type.value_counts()

NAN                  266099
Thunderstorm Wind       601
Flash Flood             463
Hail                    123
Flood                    97
Heavy Rain               81
Winter Weather           22
Strong Wind              17
Winter Storm              3
Lightning                 3
Heavy Snow                1
Debris Flow               1
Ice Storm                 1
Name: event_type, dtype: int64

In [59]:
s[s["event_type"] == "Thunderstorm Wind"]

,start_time1,trip_id,start_time,stop_time,bike_id,trip_duration,from_station_id,from_station_name,to_station_id,station_name,...,WT04,WT08,WT09,season,holiday,walk_score,transit_score,bike_score,distance,event_type
1241,2015-06-05 16:45:00,10891594,2015-06-05 16:45:00,2015-06-05 17:03:00,70435,1095,1013,Isabella St & Federal St (PNC Park),1000,Liberty Ave & Stanwix St,...,NAN,NAN,NAN,spring,0,90,96,86,0.43,Thunderstorm Wind
1242,2015-06-05 16:46:00,10891630,2015-06-05 16:46:00,2015-06-06 15:04:00,70194,80260,1001,Forbes Ave & Market Square,1001,Forbes Ave & Market Square,...,NAN,NAN,NAN,spring,0,99,100,87,0.00,Thunderstorm Wind
1243,2015-06-05 16:49:00,10891700,2015-06-05 16:49:00,2015-06-05 16:58:00,70233,496,1001,Forbes Ave & Market Square,1001,Forbes Ave & Market Square,...,NAN,NAN,NAN,spring,0,99,100,87,0.00,Thunderstorm Wind
1244,2015-06-05 16:51:00,10891737,2015-06-05 16:51:00,2015-06-05 17:04:00,70208,753,1013,Isabella St & Federal St (PNC Park),1000,Liberty Ave & Stanwix St,...,NAN,NAN,NAN,spring,0,90,96,86,0.43,Thunderstorm Wind
1245,2015-06-05 16:53:00,10891786,2015-06-05 16:53:00,2015-06-05 17:21:00,70068,1692,1047,S 22nd St & E Carson St,1047,S 22nd St & E Carson St,...,NAN,NAN,NAN,spring,0,96,65,91,0.00,Thunderstorm Wind
1246,2015-06-05 16:54:00,10891813,2015-06-05 16:54:00,2015-06-05 17:02:00,70449,451,1013,Isabella St & Federal St (PNC Park),1000,Liberty Ave & Stanwix St,...,NAN,NAN,NAN,spring,0,90,96,86,0.43,Thunderstorm Wind
1247,2015-06-05 16:58:00,10891934,2015-06-05 16:58:00,2015-06-05 17:20:00,70430,1287,1047,S 22nd St & E Carson St,1047,S 22nd St & E Carson St,...,NAN,NAN,NAN,spring,0,96,65,91,0.00,Thunderstorm Wind
1248,2015-06-05 16:59:00,10891961,2015-06-05 16:59:00,2015-06-05 17:10:00,70323,623,1005,Forbes Ave & Grant St,1049,S 12th St & E Carson St,...,NAN,NAN,NAN,spring,0,96,100,81,0.92,Thunderstorm Wind
1249,2015-06-05 17:02:00,10892020,2015-06-05 17:02:00,2015-06-05 17:10:00,70124,504,1013,Isabella St & Federal St (PNC Park),1000,Liberty Ave & Stanwix St,...,NAN,NAN,NAN,spring,0,90,96,86,0.43,Thunderstorm Wind
1250,2015-06-05 17:05:00,10892104,2015-06-05 17:05:00,2015-06-05 17:25:00,70192,1213,1001,Forbes Ave & Market Square,1049,S 12th St & E Carson St,...,NAN,NAN,NAN,spring,0,99,100,87,1.22,Thunderstorm Wind
1251,2015-06-05 17:08:00,10892160,2015-06-05 17:08:00,2015-06-05 17:23:00,70159,892,1036,Schenley Dr at Schenley Plaza (Carnegie Librar...,1024,S Negley Ave & Baum Blvd,...,NAN,NAN,NAN,spring,0,91,70,63,1.47,Thunderstorm Wind
1252,2015-06-05 17:08:00,10892163,2015-06-05 17:08:00,2015-06-05 17:32:00,70477,1418,1036,Schenley Dr at Schenley Plaza (Carnegie Librar...,1044,Zulema St & Coltart Ave,...,NAN,NAN,NAN,spring,0,91,70,63,0.53,Thunderstorm Wind
1253,2015-06-05 17:08:00,10892165,2015-06-05 17:08:00,2015-06-05 17:32:00,70436,1440,1036,Schenley Dr at Schenley Plaza (Carnegie Librar...,1044,Zulema St & Coltart Ave,...,NAN,NAN,NAN,spring,0,91,70,63,0.53,Thunderstorm Wind
1254,2015-06-05 17:12:00,10892239,2015-06-05 17:12:00,2015-06-05 17:33:00,70129,1282,1036,Schenley Dr at Schenley Plaza (Carnegie Librar...,1032,Walnut St & College St,...,NAN,NAN,NAN,spring,0,91,70,63,1.39,Thunderstorm Wind
1255,2015-06-05 17:13:00,10892271,2015-06-05 17:13:00,2015-06-05 17:54:00,70034,2430,1049,S 12th St & E Carson St,1005,Forbes Ave & Grant St,...,NAN,NAN,NAN,spring,0,85,69,92,0.92,Thunderstorm Wind
1256,2015-06-05 17:19:00,10892382,2015-06-05 17:19:00,2015-06-05 17:25:00,70020,353,1007,Stevenson St & Forbes Ave,1007,Stevenson St & Forbes Ave,...,NAN,NAN,NAN,spring,0,86,87,72,0.00,Thunderstorm Wind
1257,2015-06-05 17:36:00,10892712,2015-06-05 17:36:00,2015-06-05 17:57:00,70446,1234,1041,Fifth Ave & S Bouquet St,1018,Butler St & Stanton Ave,...,NAN,NAN,NAN,spring,0,96,71,82,1.68,Thunderstorm Wind
1258,2015-06-05 17:53:00,10893041,2015-06-05 17:53:00,2015-06-05 18:58:00,70318,3882,1005,Forbes Ave & Grant St,1032,Walnut St & College St,...,NAN,NAN,NAN,spring,0,96,100,81,3.74,Thunderstorm Wind
3980,2015-06-14 21:18:00,11211673,2015-06-14 21:18:00,2015-06-14 21:33:00,70288,890,1009,12th St & Penn Ave,1000,Liberty Ave & Stanwix St,...,NAN,NAN,NAN,spring,1,87,95,83,0.72,Thunderstorm Wind
5013,2015-06-18 19:51:00,11348274,2015-06-18 19:51:00,2015-06-18 20:20:00,70132,1789,1044,Zulema St & Coltart Ave,1022,Liberty Ave & S Millvale Ave (West Penn Hospital),...,NAN,NAN,NAN,spring,0,89,69,77,1.76,Thunderstorm Wind
5014,2015-06-18 19:53:00,11348297,2015-06-18 19:53:00,2015-06-18 20:51:00,70323,3470,1012,North Shore Trail & Fort Duquesne Bridge,1012,North Shore Trail & Fort Duquesne Bridge,...,NAN,NAN,NAN,spring,0,69,95,84,0.00,Thunderstorm Wind
5015,2015-06-18 19:53:00,11348293,2015-06-18 19:53:00,2015-06-18 20:52:00,70150,3545,1012,North Shore Trail & Fort Duquesne Bridge,1012,North Shore Trail & Fort Duquesne Bridge,...,NAN,NAN,NAN,spring,0,69,95,84,0.00,Thunderstorm Wind
5016,2015-06-18 19:56:00,11348313,2015-06-18 19:56:00,2015-06-18 20:13:00,70243,983,1041,Fifth Ave & S Bouquet St,1032,Walnut St & College St,...,NAN,NAN,NAN,spring,0,96,71,82,1.68,Thunderstorm Wind
5017,2015-06-18 19:57:00,11348320,2015-06-18 19:57:00,2015-06-18 20:16:00,70362,1138,1001,Forbes Ave & Market Square,1001,Forbes Ave & Market Square,...,NAN,NAN,NAN,spring,0,99,100,87,0.00,Thunderstorm Wind
5018,2015-06-18 19:58:00,11348326,2015-06-18 19:58:00,2015-06-18 20:09:00,70288,660,1021,Taylor St & Liberty Ave,1023,Liberty Ave & Baum Blvd,...,NAN,NAN,NAN,spring,0,89,60,95,0.74,Thunderstorm Wind
5019,2015-06-18 20:01:00,11348340,2015-06-18 20:01:00,2015-06-18 20:09:00,70094,462,1021,Taylor St & Liberty Ave,1023,Liberty Ave & Baum Blvd,...,NAN,NAN,NAN,spring,0,89,60,95,0.74,Thunderstorm Wind
5020,2015-06-18 20:12:00,11348409,2015-06-18 20:12:00,2015-06-18 20:27:00,70016,888,1019,42nd St & Butler St,1021,Taylor St & Liberty Ave,...,NAN,NAN,NAN,spring,0,86,51,77,0.71,Thunderstorm Wind
5021,2015-06-18 20:12:00,11348407,2015-06-18 20:12:00,2015-06-18 20:25:00,70061,790,1019,42nd St & Butler St,1021,Taylor St & Liberty Ave,...,NAN,NAN,NAN,spring,0,86,51,77,0.71,Thunderstorm Wind
5022,2015-06-18 20:13:00,11348410,2015-06-18 20:13:00,2015-06-18 20:26:00,70424,832,1019,42nd St & Butler St,1021,Taylor St & Liberty Ave,...,NAN,NAN,NAN,spring,0,86,51,77,0.71,Thunderstorm Wind
5023,2015-06-18 20:17:00,11348434,2015-06-18 20:17:00,2015-06-18 20:20:00,70174,211,1041,Fifth Ave & S Bouquet St,1039,Atwood St & Bates St,...,NAN,NAN,NAN,spring,0,96,71,82,0.36,Thunderstorm Wind
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241487,2018-07-15 15:40:00,53227806,2018-07-15 15:40:00,2018-07-15 15:43:00,70062,156,1013,Isabella St & Federal St (PNC Park),1013,Isabella St & Federal St (PNC Park),...,NAN,NAN,NAN,summer,1,90,96,86,0.00,Thunderstorm Wind
241488,2018-07-15 15:41:00,53227851,2018-07-15 15:41:00,2018-07-15 16:14:00,70504,2010,1000,Liberty Ave & Stanwix St,1046,S 25th St & E Carson St,...,NAN,NAN,NAN,summer,1,99,100,87,2.05,Thunderstorm Wind
241489,2018-07-15 15:41:00,53227915,2018-07-15 15:41:00,2018-07-15 16:10:00,70169,1705,1000,Liberty Ave & Stanwix St,1000,Liberty Ave & Stanwix St,...,NAN,NAN,NAN,summer,1,99,100,87,0.00,Thunderstorm Wind
241490,2018-07-15 15:41:00,53227874,2018-07-15 15:41:00,2018-07-15 16:28:00,70383,2815,1013,Isabella St & Federal St (PNC Park),1013,Isabella St & Federal St (PNC Park),...,NAN,NAN,NAN,summer,1,90,96,86,0.00,Thunderstorm Wind
241491,2018-07-15 15:41:00,53227864,2018-07-15 15:41:00,2018-07-15 16:39:00,70303,3510,1013,Isabella St & Federal St (PNC Park),1015,Federal St & E North Ave,...,NAN,NAN,NAN,summer,1,90,96,86,0.53,Thunderstorm Wind
241492,2018-07-15 15:42:00,53227921,2018-07-15 15:42:00,2018-07-15 15:50:00,70020,520,1015,Federal St & E North Ave,1010,10th St & Penn Ave (David L. Lawrence Conventi...,...,NAN,NAN,NAN,summer,1,85,71,84,0.91,Thunderstorm Wind
241493,2018-07-15 15:42:00,53227989,2018-07-15 15:42:00,2018-07-15 16:07:00,70606,1475,1045,S 27th St & Sidney St. (Southside Works),1003,First Ave & Smithfield St,...,NAN,NAN,NAN,summer,1,86,64,84,1.94,Thunderstorm Wind
241494,2018-07-15 15:42:00,53227983,2018-07-15 15:42:00,2018-07-15 16:26:00,70466,2617,1013,Isabella St & Federal St (PNC Park),1013,Isabella St & Federal St (PNC Park),...,NAN,NAN,NAN,summer,1,90,96,86,0.00,Thunderstorm Wind
241495,2018-07-15 15:42:00,53227945,2018-07-15 15:42:00,2018-07-15 16:52:00,70460,4198,1012,North Shore Trail & Fort Duquesne Bridge,1000,Liberty Ave & Stanwix St,...,NAN,NAN,NAN,summer,1,69,95,84,0.38,Thunderstorm Wind
241496,2018-07-15 15:43:00,53228037,2018-07-15 15:43:00,2018-07-15 16:54:00,70167,4211,1012,North Shore Trail & Fort Duquesne Bridge,1000,Liberty Ave & Stanwix St,...,NAN,NAN,NAN,summer,1,69,95,84,0.38,Thunderstorm Wind
241497,2018-07-15 15:45:00,53228132,2018-07-15 15:45:00,2018-07-15 16:51:00,70467,4007,1012,North Shore Trail & Fort Duquesne Bridge,1000,Liberty Ave & Stanwix St,...,NAN,NAN,NAN,summer,1,69,95,84,0.38,Thunderstorm Wind
241498,2018-07-15 15:45:00,53228136,2018-07-15 15:45:00,2018-07-15 16:26:00,70005,2469,1013,Isabella St & Federal St (PNC Park),1013,Isabella St & Federal St (PNC Park),...,NAN,NAN,NAN,summer,1,90,96,86,0.00,Thunderstorm Wind
241512,2018-07-15 16:30:00,53230789,2018-07-15 16:30:00,2018-07-15 21:32:00,70507,18121,1047,S 22nd St & E Carson St,1047,S 22nd St & E Carson St,...,NAN,NAN,NAN,summer,1,96,65,91,0.00,Thunderstorm Wind
241513,2018-07-15 16:43:00,53231378,2018-07-15 16:43:00,2018-07-15 16:45:00,70138,123,1000,Liberty Ave & Stanwix St,1000,Liberty Ave & Stanwix St,...,NAN,NAN,NAN,summer,1,99,100,87,0.00,Thunderstorm Wind
241514,2018-07-15 16:43:00,53231373,2018-07-15 16:43:00,2018-07-15 16:44:00,70576,103,1000,Liberty Ave & Stanwix St,1000,Liberty Ave & Stanwix St,...,NAN,NAN,NAN,summer,1,99,100,87,0.00,Thunderstorm Wind
241515,2018-07-15 16:55:00,53231914,2018-07-15 16:55:00,2018-07-15 17:03:00,70277,470,1045,S 27th St & Sidney St. (Southside Works),1048,S 18th St & Sidney St,...,NAN,NAN,NAN,summer,1,86,64,84,0.81,Thunderstorm Wind
241516,2018-07-15 17:11:00,53232586,2018-07-15 17:11:00,2018-07-15 18:34:00,70161,4974,1017,21st St & Penn Ave,1010,10th St & Penn Ave (David L. Lawrence Conventi...,...,NAN,NAN,NAN,summer,1,70,65,85,0.83,Thunderstorm Wind
248038,2018-08-05 13:07:00,55171704,2018-08-05 13:07:00,2018-08-05 13:10:00,70489,213,1046,S 25th St & E Carson St,1047,S 22nd St & E Carson St,...,NAN,NAN,NAN,summer,1,94,65,89,0.25,Thunderstorm Wind
248039,2018-08-05 13:09:00,55171965,2018-08-05 13:09:00,2018-08-05 13:37:00,70640,1662,1015,Federal St & E North Ave,1002,Third Ave & Wood St,...,NAN,NAN,NAN,summer,1,85,71,84,1.13,Thunderstorm Wind
248040,2018-08-05 13:13:00,55172486,2018-08-05 13:13:00,2018-08-05 15:58:00,70394,9891,1045,S 27th St & Sidney St. (Southside Works),1001,Forbes Ave & Market Square,...,NAN,NAN,NAN,summer,1,86,64,84,2.16,Thunderstorm Wind
248041,2018-08-05 13:13:00,55172485,2018-08-05 13:13:00,2018-08-05 16:00:00,70455,9987,1045,S 27th St & Sidney St. (Southside Works),1001,Forbes Ave & Market Square,...,NAN,NAN,NAN,summer,1,86,64,84,2.16,Thunderstorm Wind
248042,2018-08-05 13:16:00,55172759,2018-08-05 13:16:00,2018-08-05 13:45:00,70644,1733,1045,S 27th St & Sidney St. (Southside Works),1003,First Ave & Smithfield St,...,NAN,NAN,NAN,summer,1,86,64,84,1.94,Thunderstorm Wind
248043,2018-08-05 13:16:00,55172760,2018-08-05 13:16:00,2018-08-05 13:47:00,70344,1897,1045,S 27th St & Sidney St. (Southside Works),1000,Liberty Ave & Stanwix St,...,NAN,NAN,NAN,summer,1,86,64,84,2.25,Thunderstorm Wind
248044,2018-08-05 13:16:00,55172844,2018-08-05 13:16:00,2018-08-05 13:48:00,70104,1876,1045,S 27th St & Sidney St. (Southside Works),1000,Liberty Ave & Stanwix St,...,NAN,NAN,NAN,summer,1,86,64,84,2.25,Thunderstorm Wind
259135,2018-09-21 19:55:00,59589917,2018-09-21 19:55:00,2018-09-21 20:00:00,70531,348,1038,Boulevard of the Allies & Parkview Ave,1038,Boulevard of the Allies & Parkview Ave,...,NAN,NAN,NAN,summer,0,78,61,60,0.00,Thunderstorm Wind
259136,2018-09-21 20:06:00,59590133,2018-09-21 20:06:00,2018-09-21 20:13:00,70581,404,1015,Federal St & E North Ave,1011,Fort Duquesne Blvd & 7th St,...,NAN,NAN,NAN,summer,0,85,71,84,0.77,Thunderstorm Wind
259137,2018-09-21 20:07:00,59590145,2018-09-21 20:07:00,2018-09-21 20:16:00,70394,533,1015,Federal St & E North Ave,1011,Fort Duquesne Blvd & 7th St,...,NAN,NAN,NAN,summer,0,85,71,84,0.77,Thunderstorm Wind
259138,2018-09-21 20:13:00,59590268,2018-09-21 20:13:00,2018-09-22 11:37:00,70522,55468,1014,Ridge Ave & Brighton Rd (CCAC),1014,Ridge Ave & Brighton Rd (CCAC),...,NAN,NAN,NAN,summer,0,80,77,79,0.00,Thunderstorm Wind
259139,2018-09-21 20:16:00,59590330,2018-09-21 20:16:00,2018-09-22 11:35:00,70662,55155,1048,S 18th St & Sidney St,1048,S 18th St & Sidney St,...,NAN,NAN,NAN,summer,0,95,68,90,0.00,Thunderstorm Wind
259140,2018-09-21 20:17:00,59590342,2018-09-21 20:17:00,2018-09-21 20:20:00,70666,191,1006,Ross St & Sixth Ave (Steel Plaza T Station),1006,Ross St & Sixth Ave (Steel Plaza T Station),...,NAN,NAN,NAN,summer,0,98,100,66,0.00,Thunderstorm Wind

In [61]:
#exporting as csv
b= s.to_csv("rental_storm.csv", index = 0)